apiVersion: v1
kind: PersistentVolume
metadata:
  name: datashare-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data
    server: monitoring.internal
